apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: secure-topic-reader
  namespace: amq-streams
  labels:
    strimzi.io/cluster: production-ready
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic lines using consumer group secure-group
      - resource:
          type: topic
          name: lines
          patternType: literal
        operations:
          - Read
          - Describe
        host: "*"
      # Example ACL rules for producing to topic my-topic
      - resource:
          type: group
          name: secure-group
          patternType: literal
        operations:
          - Read
        host: "*"