apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: secure-topic-writer
  namespace: amq-streams
  labels:
    strimzi.io/cluster: production-ready
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example Producer Acls for topic secure-topic
      - resource:
          type: topic
          name: lines
          patternType: literal
        operations:
          - Write
        host: "*"