apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-workshop
  name: log-consumer
  namespace: amq-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-workshop
      name: log-consumer
  template:
    metadata:
      labels:
        app: kafka-workshop
        name: log-consumer
    spec:
      containers:
      - image: docker.io/mbogoevici/log-consumer:latest
        name: log-consumer
        env:
        - name: CAMEL_COMPONENT_KAFKA_CONFIGURATION_BROKERS
          value: "production-ready-kafka-bootstrap.team-1.svc:9092"