apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-workshop
  name: timer-producer
  namespace: amq-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-workshop
      name: timer-producer
  template:
    metadata:
      labels:
        app: kafka-workshop
        name: timer-producer
    spec:
      containers:
      - image: docker.io/mbogoevici/timer-producer:latest
        name: timer-producer
        env:
        - name: CAMEL_COMPONENT_KAFKA_CONFIGURATION_BROKERS
          value: "production-ready-kafka-bootstrap.amq-streams.svc:9092"
        - name: CAMEL_COMPONENT_KAFKA_CONFIGURATION_SASL_MECHANISM
          value: SCRAM-SHA-512
        - name: CAMEL_COMPONENT_KAFKA_CONFIGURATION_SECURITY_PROTOCOL
          value: SASL_PLAINTEXT
        - name: KAFKA_USER
          value: secure-topic-writer
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: secure-topic-writer
        - name: CAMEL_COMPONENT_KAFKA_CONFIGURATION_SASL_JAAS_CONFIG
          value: org.apache.kafka.common.security.scram.ScramLoginModule required username='${KAFKA_USER}' password='${KAFKA_PASSWORD}';