== Topic Management

In the next module we will focus on creating and managing topics.
In AMQ Streams, topics are managed through a KafkaTopic resource.

=== Creating a topics

Let's create a topic into our project.
The structure and the create command of a `KafkaTopic` custom resource is outlined below.

----
cat << EOF | oc apply -f -
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: lines
  namespace: amq-streams
  labels:
    strimzi.io/cluster: production-ready
spec:
  partitions: 2
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
EOF
----

Notice a few important attributes:

* `metadata.name` which is the name of the topic
* `metadata.labels[strimzi.io/cluster]` which is the target cluster for the topic (remember that you could have more) than one cluster in the same namespace;
* `spec.partitions` which is the partition count of the topic
* `spec.replicas` which is the number of replicas per partition
* `spec.config` which contains miscellaneous configuration options, such as retention time and segment size

Let's wait a number of seconds and let's try to check that the topic has been created and log into one of the Kafka pods.
You can use the command below or use the web console and the Terminal tab.

----
oc rsh production-ready-kafka-0
----

Let's get the topic information.

----
bin/kafka-topics.sh --bootstrap-server localhost:9092 --topic lines --describe
----

The expected result should look like:

----
Topic: lines	TopicId: XudDfYxYT5egMhIeMsceig	PartitionCount: 2	ReplicationFactor: 2	Configs: segment.bytes=1073741824,retention.ms=7200000,message.format.version=3.0-IV1
	Topic: lines	Partition: 0	Leader: 2	Replicas: 2,1	Isr: 2,1
	Topic: lines	Partition: 1	Leader: 1	Replicas: 1,0	Isr: 1,0
----

Exit the container shell.

Now let's increase the number of partitions.

----
cat << EOF | oc apply -f -
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: lines
  namespace: amq-streams
  labels:
    strimzi.io/cluster: production-ready
spec:
  partitions: 10
  replicas: 2
  config:
    retention.ms: 14400000
    segment.bytes: 1073741824
EOF
----

And let's get the topic information again.
The topic has now 10 partitions and also note the increased retention time.

----
oc rsh production-ready-kafka-0

bin/kafka-topics.sh --bootstrap-server localhost:9092 --topic lines --describe
Topic: lines	TopicId: XudDfYxYT5egMhIeMsceig	PartitionCount: 10	ReplicationFactor: 2	Configs: segment.bytes=1073741824,retention.ms=14400000,message.format.version=3.0-IV1
	Topic: lines	Partition: 0	Leader: 2	Replicas: 2,1	Isr: 2,1
	Topic: lines	Partition: 1	Leader: 1	Replicas: 1,0	Isr: 1,0
	Topic: lines	Partition: 2	Leader: 1	Replicas: 1,2	Isr: 1,2
	Topic: lines	Partition: 3	Leader: 2	Replicas: 2,1	Isr: 2,1
	Topic: lines	Partition: 4	Leader: 0	Replicas: 0,2	Isr: 0,2
	Topic: lines	Partition: 5	Leader: 1	Replicas: 1,0	Isr: 1,0
	Topic: lines	Partition: 6	Leader: 2	Replicas: 2,0	Isr: 2,0
	Topic: lines	Partition: 7	Leader: 0	Replicas: 0,1	Isr: 0,1
	Topic: lines	Partition: 8	Leader: 1	Replicas: 1,2	Isr: 1,2
	Topic: lines	Partition: 9	Leader: 2	Replicas: 2,1	Isr: 2,1
----

We can now exit the container.

----
exit
----

Now that the topic has been created, we can start running some applications.
