== Understanding the application ecosystem

For illustrating the different features of AMQ Streams, we will use a consumer application and a producer application based on the Kafka consumer and producer API.
The source code of the applications is available in https://github.com/RedHat-Middleware-Workshops/workshop-amq-streams/tree/master/apps[GitHub].
In this example we use containerized versions of the applications and we will monitor the impact.

Let's connect the applications to the production cluster we just created.

First, we deploy the producer that will periodically emit messages on a topic named `lines`.
Note the `CAMEL_COMPONENT_KAFKA_CONFIGURATION_BROKERS` environment variable that sets the bootstrap broker(s) for the application.
The descriptor and the deploy command for the application is below.

----
cat << EOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-workshop
  name: timer-producer
  namespace: amq-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-workshop
      name: timer-producer
  template:
    metadata:
      labels:
        app: kafka-workshop
        name: timer-producer
    spec:
      containers:
      - image: docker.io/mbogoevici/timer-producer:latest
        name: timer-producer
        env:
        - name: CAMEL_COMPONENT_KAFKA_CONFIGURATION_BROKERS
          value: "production-ready-kafka-bootstrap.amq-streams.svc:9092"
EOF
----

We also deploy a simple application that consumes messages.

----
cat << EOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-workshop
  name: log-consumer
  namespace: amq-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-workshop
      name: log-consumer
  template:
    metadata:
      labels:
        app: kafka-workshop
        name: log-consumer
    spec:
      containers:
      - image: docker.io/mbogoevici/log-consumer:latest
        name: log-consumer
        env:
        - name: CAMEL_COMPONENT_KAFKA_CONFIGURATION_BROKERS
          value: "production-ready-kafka-bootstrap.amq-streams.svc:9092"
        - name: CAMEL_COMPONENT_KAFKA_CONFIGURATION_GROUP_ID
          value: test-group
EOF
----

Make sure that everything works and all the applications are started, then we will validate that the applications communicate with each other.

First, wait until the producer and consumer pods are running.

----
oc get pods -l app=kafka-workshop -n amq-streams

NAME                              READY   STATUS    RESTARTS   AGE
log-consumer-5874676f74-zdc5t     1/1     Running   0          2m21s
timer-producer-6bf5c9b768-d2rmg   1/1     Running   0          5m59s
----

Get the name of the consumer pod.

----
CONSUMER_POD_NAME=$(oc get pods -l app=kafka-workshop -l name=log-consumer -n amq-streams -o jsonpath='{.items[0].metadata.name}')

echo $CONSUMER_POD_NAME
----

Now let's tail the logs from the consumer (use the pod name retrieved in the previous step).

----
oc logs -f pod/$CONSUMER_POD_NAME  -c log-consumer --tail=-1
----

We expect the output to look like as follows:

----
2024-03-17 22:27:35.377  INFO 1 --- [Consumer[lines]] route1                                   : Message 125 at Sun Mar 17 22:27:35 UTC 2024
2024-03-17 22:27:40.379  INFO 1 --- [Consumer[lines]] route1                                   : Message 126 at Sun Mar 17 22:27:40 UTC 2024
2024-03-17 22:27:45.377  INFO 1 --- [Consumer[lines]] route1                                   : Message 127 at Sun Mar 17 22:27:45 UTC 2024
2024-03-17 22:27:50.479  INFO 1 --- [Consumer[lines]] route1                                   : Message 128 at Sun Mar 17 22:27:50 UTC 2024
2024-03-17 22:27:55.378  INFO 1 --- [Consumer[lines]] route1                                   : Message 129 at Sun Mar 17 22:27:55 UTC 2024
----

Messages should continue to arrive every five seconds, and this indicates that the two applications communicate with each other.

Now let's delete the two applications.

----
oc delete deployment log-consumer -n amq-streams
oc delete deployment timer-producer -n amq-streams
----
